/-
Trusted PF verifier (harness side). Run as:
  lean --run EqVerify.lean <AnswerModule> <StatementModule> <theoremName>
with LEAN_PATH containing the directory of both compiled modules and the Mathlib build.

* <StatementModule> (EqStmt) is generated by check_lean.sh from the pristine fixture statement only (it imports
  Mathlib and declares `eq_pristine_stmt : Prop := <statement>`), so nothing in the answer can influence how the
  statement is elaborated.
* The answer module's own constants are replayed through the kernel on top of its imports plus EqStmt, exactly as
  core `leanchecker` does (`Kernel.Environment.replay`, the code of `LeanChecker.replayFromImports`). Unsafe and
  partial constants are not replayed, so a theorem depending on them fails to replay.
* In the replayed environment the answer's constant `<theoremName>` must be a theorem or definition defined by the
  answer, its type must equal the pristine statement (alpha-equivalence, else kernel definitional equality), and
  the axioms it uses transitively (computed here by walking the replayed constants, not from any cached extension)
  must be among propext, Classical.choice, Quot.sound.
Prints `PASS` (exit 0) or `FAIL: <reason>` (exit 1); usage or environment errors exit 2.
-/
import Lean.CoreM
import Lean.Replay

open Lean

def allowedAxioms : List Name := [``propext, ``Classical.choice, ``Quot.sound]

/-- Axioms reachable from `root` in `env`, and referenced names missing from `env`. -/
def axiomsOf (env : Kernel.Environment) (root : Name) : Array Name × Array Name := Id.run do
  let mut seen : NameSet := {}
  let mut todo : Array Name := #[root]
  let mut axs : Array Name := #[]
  let mut miss : Array Name := #[]
  while todo.size > 0 do
    let n := todo.back!
    todo := todo.pop
    if seen.contains n then continue
    seen := seen.insert n
    match env.find? n with
    | none => miss := miss.push n
    | some ci =>
      if let .axiomInfo _ := ci then axs := axs.push n
      for c in ci.getUsedConstantsAsSet.toList do
        unless seen.contains c do todo := todo.push c
  return (axs, miss)

def fail (msg : String) : IO UInt32 := do
  IO.println s!"FAIL: {msg}"
  return 1

unsafe def main (args : List String) : IO UInt32 := do
  let [ansMod, stmtMod, thmName] := args
    | IO.eprintln "usage: lean --run EqVerify.lean <AnswerModule> <StatementModule> <theoremName>"; return 2
  initSearchPath (← findSysroot)
  let ans := ansMod.toName
  let mFile ← findOLean ans
  unless (← mFile.pathExists) do
    IO.eprintln s!"object file '{mFile}' of module {ans} does not exist"; return 2
  let mut fnames := #[mFile]
  let sFile := OLeanLevel.server.adjustFileName mFile
  if (← sFile.pathExists) then
    fnames := fnames.push sFile
    let pFile := OLeanLevel.private.adjustFileName mFile
    if (← pFile.pathExists) then
      fnames := fnames.push pFile
  let parts ← readModuleDataParts fnames
  if h : parts.size = 0 then
    IO.eprintln "failed to read module data"; return 2
  else
  let (mod, _) := parts[0]
  let imports := mod.imports.push { module := stmtMod.toName }
  let (_, s) ← importModulesCore imports |>.run
  let env ← finalizeImport s imports {} 0 false false (isModule := true)
  let mut newConstants : Std.HashMap Name ConstantInfo := {}
  for name in parts[parts.size-1].1.constNames, ci in parts[parts.size-1].1.constants do
    newConstants := newConstants.insert name ci
  let kenv ← try env.toKernelEnv.replay newConstants
    catch e => return (← fail s!"kernel replay rejected the answer: {e}")
  let fenv := Environment.ofKernelEnv kenv
  let thm := thmName.toName
  unless newConstants.contains thm do
    return (← fail s!"the answer does not declare a top-level constant named {thm}")
  let some ci := kenv.find? thm
    | return (← fail s!"{thm} is not in the kernel-replayed environment (unsafe or partial?)")
  match ci with
  | .thmInfo _ | .defnInfo _ => pure ()
  | _ => return (← fail s!"{thm} is not a theorem or definition")
  let some sci := kenv.find? `eq_pristine_stmt
    | IO.eprintln "statement module lacks eq_pristine_stmt"; return 2
  let some stmt := sci.value?
    | IO.eprintln "eq_pristine_stmt has no value"; return 2
  if ci.type == stmt then IO.println "INFO: statement matched syntactically (alpha-equivalence)"
  unless ci.type == stmt do
    match Kernel.isDefEq fenv {} ci.type stmt with
    | .ok true => IO.println "INFO: statement matched by kernel definitional equality"
    | .ok false => return (← fail s!"statement mismatch: the type of {thm} is not the fixture statement")
    | .error _ => return (← fail s!"statement mismatch: kernel could not compare the type of {thm} with the fixture statement")
  let (axs, miss) := axiomsOf kenv thm
  unless miss.isEmpty do
    return (← fail s!"constants missing from the replayed environment: {miss.toList.take 5}")
  let bad := axs.filter (fun a => !allowedAxioms.contains a)
  unless bad.isEmpty do
    return (← fail s!"non-standard axioms {bad.toList}")
  env.freeRegions
  IO.println "PASS"
  return 0
