# /// script
# requires-python = ">=3.11"
# dependencies = ["pytest", "numpy==2.5.3", "jsonschema==4.26.0"]
# ///
"""Seeded-mutation run: each mutation is applied to a temp copy of the package and the tests that guard it must fail.

Run from anywhere: uv run --script harness/tests/mutations.py   (exit 0 iff every mutation is killed and the
unmutated copy passes the same selections). `--only M137,M140` runs the named mutants only (the base run then covers
their selections only): a light per-mutant proof while the full run waits.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

HARNESS = Path(__file__).resolve().parent.parent
STAGE = HARNESS.parent
T_ARGV = "test_isolation.py::test_container_argv_has_every_required_flag_and_only_two_mounts"
TUNNEL_SH = "../lib/eq-container/probe.d/50-tunnel.sh"


def container_dir() -> Path | None:
    """The repo's lib/eq-container ($EQ_CONTAINER_DIR, else beside the stage), as conftest.container_dir()."""
    for d in ([Path(os.environ["EQ_CONTAINER_DIR"])] if os.environ.get("EQ_CONTAINER_DIR") else []) + \
            [STAGE / "lib" / "eq-container", STAGE.parent / "lib" / "eq-container"]:
        if (d / "lib.sh").is_file():
            return d
    return None

# (id, guarded property, file, old, new, test selections); `old` may be a list of (old, new) pairs (then new = "")
MUTATIONS: list[tuple[str, str, str, Any, str, list[str]]] = [
    ("M01", "Latin-square balance of perm views", "eq_harness.py",
     "return (i * s // n) % s", "return ((i // 2) * s // n) % s",
     ["test_views.py::test_perm_latin_square_when_n_equals_s"]),
    ("M02", "exact k-cover counts", "eq_harness.py",
     "ids = [i, (i + 1) % 4]", "ids = [i, (i + 1) % 3]",
     ["test_views.py::test_kcover_exact_counts"]),
    ("M03", "reducer determinism (plurality representative)", "eq_harness.py",
     "min(raws, key=lambda a: json.dumps(a, sort_keys=True)) if raws else None", "raws[0] if raws else None",
     ["test_reducers.py::test_plurality_invariant_under_permutation_with_ties"]),
    ("M04", "reducer determinism (finding clusters)", "eq_harness.py",
     "srt = sorted(findings, key=lambda f: f.sort_key)", "srt = list(findings)",
     ["test_reducers.py::test_cluster_findings_order_free"]),
    ("M05", "seeded tie-break", "eq_harness.py",
     "return c[int(np.random.default_rng(seed).integers(len(c)))]", "return c[0]",
     ["test_reducers.py::test_tie_break_is_seeded_and_order_free"]),
    ("M06", "quorum tau rule", "eq_harness.py",
     "return math.ceil(tf * n)", "return math.floor(tf * n) + 1",
     ["test_quorum_seeds.py::test_quorum_tau_is_ceil_tau_n"]),
    ("M07", "quorum ceil(2N/3) rule", "eq_harness.py",
     "return -((-2 * n) // 3)", "return (2 * n) // 3",
     ["test_quorum_seeds.py::test_quorum_values"]),
    ("M08", "evidence gate (unverified change accepted)", "eq_harness.py",
     "    if verified:\n        return GateDecision(new_answer",
     "    if fresh:\n        return GateDecision(new_answer",
     ["test_gate.py"]),
    ("M09", "seed reproducibility (§8.4 / seeds.out)", "eq_harness.py",
     "return SEED_BASE ^ int(hashlib.sha256(tag.encode()).hexdigest()[:8], 16)",
     "return SEED_BASE ^ int(hashlib.sha256(tag.encode()).hexdigest()[:7], 16)",
     ["test_quorum_seeds.py::test_seeds_match_seeds_out_and_formula"]),
    ("M10", "cap arithmetic Σ caps <= B", "eq_harness.py",
     "rest = pool - n * floor_each", "rest = pool",
     ["test_caps.py::test_g_and_eg_caps_sum_le_b"]),
    ("M11", "argv-only launches (no shell=True)", "eq_harness.py",
     'timeout=int(self.flags["call_timeout_s"]), shell=False,',
     'timeout=int(self.flags["call_timeout_s"]), shell=True,',
     ["test_launch.py::test_no_shell_anywhere_in_harness"]),
    ("M12", "grader-input blinding", "eq_harness.py",
     '    s = ROLE_TOKEN_RE.sub("[redacted]", s)\n', "",
     ["test_blinding.py"]),
    ("M13", "no haiku: flags default (D3 per-agent map, re-anchored 2026-10-06)", "eq_harness.py",
     '"coder": "sonnet", "data-engineer": "sonnet",', '"coder": "claude-haiku-4-5", "data-engineer": "sonnet",',
     ["test_launch.py::test_no_haiku_anywhere"]),
    ("M14", "no haiku: stub output", "stub_claude",
     '"total_cost_usd": cost, "model": model,', '"total_cost_usd": cost, "model": "claude-haiku-4-5",',
     ["test_launch.py::test_no_haiku_anywhere"]),
    ("M15", "fresh fixture copy per call", "eq_harness.py",
     'workdir = base / "work" / cid', 'workdir = base / "work" / "shared"',
     ["test_launch.py::test_fresh_fixture_copy_per_call"]),
    ("M16", "eq_check E3 install drift", "eq_check.sh",
     'if [ "$n_bad" = 0 ]; then', "if true; then",
     ["test_shell.py::test_check_fault_install_drift"]),
    ("M17", "eq_check E6 open c-arm", "eq_check.sh",
     'if [ -z "$open_arms" ]; then', "if true; then",
     ["test_shell.py::test_check_fault_open_c_arm"]),
    ("M18", "eq_check E10 concurrent claude process", "eq_check.sh",
     'if [ -z "$others" ] && [ "${nproc:-0}" = 0 ]; then', 'if [ -z "$others" ]; then',
     ["test_shell.py::test_check_fault_concurrent_claude"]),
    ("M19", "eq_check E5 c0 not collected", "eq_check.sh",
     'if [ -f "$C0/FROZEN_AT.txt" ] && [ -f "$C0/MANIFEST.sha256" ]; then ok', "if true; then ok",
     ["test_shell.py::test_check_fault_c0_not_collected"]),
    ("M20", "eq_check E11 spend ceiling", "eq_check.sh",
     "s + 4*b <= c", "s + b <= c",
     ["test_shell.py::test_check_fault_spend_ceiling"]),
    ("M21", "eq_freeze refuses without c0", "eq_freeze.sh",
     '[ -f "$C0/FROZEN_AT.txt" ] || die', 'true || die',
     ["test_shell.py::test_freeze_refuses_without_c0"]),
    ("M26", "perm view: floor rule (the drafts' ceil rule restored in the generator)", "eq_harness.py",
     "return (i * s // n) % s", "return (i * -(-s // n)) % s",
     ["test_views.py::test_perm_no_collision_where_ceil_collided", "test_views.py::test_perm_balance_n5_default_rule"]),
    ("M27", "perm view: flags.json default restored to ceil", "eq_harness.py",
     '"perm_shift_rule": "floor",', '"perm_shift_rule": "ceil",',
     ["test_views.py::test_perm_no_collision_where_ceil_collided"]),
    ("M22", "RS answer key (rationale must not split clusters)", "eq_harness.py",
     "    if not spec:\n        return normalise_answer\n",
     "    if not spec or True:\n        return normalise_answer\n",
     ["test_review_fixes.py::test_rs_key_ignores_rationale_and_splits_refuted_values"]),
    ("M23", "file evidence read from the pristine fixture, not the member's copy", "eq_harness.py",
     "                    item.pool_dir / item.fixture if item.fixture is not None else None, item.fixture or \"\",",
     "                    Path(\"/nonexistent\"), item.fixture or \"\",",
     ["test_gate.py::test_reconcile_end_to_end"]),
    ("M24", "member copies writable although the frozen pool is read-only", "eq_harness.py",
     "q.chmod(q.stat().st_mode | stat.S_IWUSR | (stat.S_IXUSR if q.is_dir() else 0))", "pass",
     ["test_review_fixes.py::test_copy_from_read_only_pool_is_writable"]),
    ("M25", "public check answer never written into the member's copy", "eq_harness.py",
     'd = self.arm_dir(item, label) / "check_inputs"', "d = workdir",
     ["test_review_fixes.py::test_check_never_writes_into_the_copy_and_gets_a_minimal_env"]),
    # ---- eq_mediator (MEDIATOR.md §7) ----
    ("M28", "Shapley weights (efficiency: sum phi = v(N) - v(empty))", "eq_mediator.py",
     "Fraction(math.factorial(r) * math.factorial(n - r - 1), math.factorial(n))",
     "Fraction(math.factorial(r) * math.factorial(n - r), math.factorial(n))",
     ["test_mediator.py::test_shapley_sums_to_v_full_minus_v_empty", "test_mediator.py::test_shapley_aaabc_example"]),
    ("M29", "verify(): each run in a FRESH fixture copy", "eq_mediator.py",
     '                wd = tmp_root / f"run{k}"\n                eh.copy_tree_writable(fixture, wd)',
     '                wd = tmp_root / "run0"\n'
     '                if k == 0:\n                    eh.copy_tree_writable(fixture, wd)',
     ["test_mediator.py::test_verify_runs_twice_in_fresh_copies"]),
    ("M30", "verify(): argv allow-list", "eq_mediator.py",
     "allowed = bool(argv) and (", "allowed = bool(argv) or (",
     ["test_mediator.py::test_verify_refuses_non_allow_listed"]),
    ("M31", "verify(): minimal environment", "eq_mediator.py",
     "eh.run_bounded(argv, wd, eh.minimal_env(TMPDIR=str(tmp)), timeout_s)",
     "eh.run_bounded(argv, wd, dict(eh.os.environ), timeout_s)",
     ["test_mediator.py::test_verify_minimal_env_and_timeout"]),
    ("M32", "verify(): timeout", "eq_mediator.py",
     "eh.run_bounded(argv, wd, eh.minimal_env(TMPDIR=str(tmp)), timeout_s)",
     "eh.run_bounded(argv, wd, eh.minimal_env(TMPDIR=str(tmp)), 3600.0)",
     ["test_mediator.py::test_verify_minimal_env_and_timeout"]),
    ("M33", "R1 veto", "eq_mediator.py",
     "keep = [o for o in outs if o.member not in v]", "keep = list(outs)",
     ["test_mediator.py::test_r1_veto"]),
    ("M34", "R3 fact cap (3 per member)", "eq_mediator.py",
     "if len(seen) == MAX_FACTS_PER_MEMBER:", "if len(seen) == 99:",
     ["test_mediator.py::test_r3_facts_only_cap_and_kinds"]),
    ("M35", "ENS: a 3-way split goes to R1", "eq_mediator.py",
     "            return trio[i]\n    return r1", "            return trio[i]\n    return r0",
     ["test_mediator.py::test_r2_and_ens"]),
    ("M36", "order-free reducers (member order must not matter)", "eq_mediator.py",
     [("    return sorted(outs, key=lambda o: o.member)", "    return list(outs)"),
      ("    win = tied[0] if len(tied) == 1 else eh.tie_break(tied, ctx.tie_seed)", "    win = tied[0]")],
     "", ["test_mediator.py::test_reducers_and_shapley_order_free"]),
    ("M37", "fact dedupe (each distinct fact checked once)", "eq_mediator.py",
     "            if k in self.facts:\n                return self.facts[k]\n", "",
     ["test_mediator.py::test_fact_checker_dedupe_and_budget"]),
    ("M38", "decisive facts: only evidence-gated changes are reverted", "eq_mediator.py",
     'if c.get("gate") == "evidence" and f in', 'if f in',
     ["test_mediator.py::test_loo_and_decisive_facts"]),
    ("M40", "answer file written without following a planted symlink", "eq_harness.py",
     "    if p.is_symlink() or p.is_file():\n        p.unlink()\n    elif p.exists():",
     "    if False:\n        p.unlink()\n    elif p.exists() and not p.is_symlink():",
     ["test_review_fixes.py::test_answer_file_never_follows_a_planted_symlink"]),
    ("M41", "k-cover: pinned (source) segments in every partial view", "eq_harness.py",
     "    seen = sorted(pin | {free[k] for k in blocks[ids[0]]}",
     "    seen = sorted({free[k] for k in blocks[ids[0]]}",
     ["test_views.py::test_kcover_pinned_in_every_view"]),
    ("M42", "CR grader rids relabelled per answer (oracle rid f<i> is not unique across answers)", "eq_harness.py",
     [('        out = {"rid": tok, "type": rec["type"]',
       '        out = {"rid": str(rec.get("rid")), "type": rec["type"]'),
      ('        key[tok] = {"unit": cr_unit_key(u), "rid": str(rec.get("rid"))}',
       '        key[str(rec.get("rid"))] = {"unit": cr_unit_key(u), "rid": str(rec.get("rid"))}')],
     "", ["test_cr_grading.py::test_relabel_unique_blind_and_order_free"]),
    ("M43", "CR verdicts routed back to their own answer", "eq_harness.py",
     '        out.setdefault(t["unit"], []).append(',
     '        out.setdefault(next(iter(tokens.values()))["unit"], []).append(',
     ["test_cr_grading.py::test_split_verdicts_routes_and_validates"]),
    ("M44", 'ES oracle score "inf" (string) parsed as infinity', "eq_harness.py",
     'x.strip().lower().lstrip("+") in ("inf", "infinity")', 'x.strip().lower().lstrip("+") in ("infinity",)',
     ["test_cr_grading.py::test_parse_score_handles_inf"]),
    # ---- security review 2026-10-04 (proofs: tests/test_eqsec_proofs.py) ----
    ("M45", "H1 dependency outputs never written through a planted link", "eq_harness.py",
     '            put_deps(wd, {d: base / f"{d}.json" for d in nd.deps})',
     '            (wd / ".eq_deps").mkdir(exist_ok=True)\n'
     '            for d in nd.deps:\n'
     '                shutil.copyfile(base / f"{d}.json", wd / ".eq_deps" / f"{d}.json")',
     ["test_eqsec_proofs.py::test_h1_dep_write_does_not_follow_planted_symlink"]),
    ("M46", "H2 the check never runs member-edited check files", "eq_harness.py",
     [("check_copy(item, workdir, cdir, overlay=not fname, owned=self.owned_paths(item))",
       "check_copy(item, workdir, cdir, overlay=True, owned=())")], "",
     ["test_eqsec_proofs.py::test_h2_tampered_check_does_not_pass"]),
    ("M47", "H2 (CP) owned paths kept pristine in the check copy", "eq_harness.py",
     "            if any(rel == o or rel.startswith(o + \"/\") for o in own) or not",
     "            if False or not",
     ["test_review_fixes.py::test_check_copy_cp_overlay_keeps_tests_and_ignores_planted_files"]),
    ("M48", "H3 fact budget counts checking time only", "eq_mediator.py",
     "            if self.spent > self.budget_s:", "            if self.clock() > self.budget_s:",
     ["test_eqsec_proofs.py::test_h3_budget_counts_checking_time_only"]),
    ("M49", "H3 evidence per call capped at 8", "eq_harness.py",
     "        return self.evidence_all[:MAX_EVIDENCE]", "        return self.evidence_all",
     ["test_eqsec_proofs.py::test_h3_evidence_per_call_is_capped"]),
    ("M50", "M4 member text quoted in other models' prompts", "eq_mediator.py",
     "    return json.dumps(str(s)[:cap], ensure_ascii=True)", "    return str(s)[:cap]",
     ["test_eqsec_proofs.py::test_m4_summary_cannot_be_forged"]),
    ("M51", "M5 check output bounded in memory", "eq_harness.py",
     "                del buf[: len(buf) - keep]", "                pass",
     ["test_eqsec_proofs.py::test_m5_check_output_bounded_in_memory"]),
    ("M52", "M5 timeout kills the whole process group", "eq_harness.py",
     "            os.killpg(p.pid, signal.SIGKILL)", "            p.kill()",
     ["test_eqsec_proofs.py::test_m5_timeout_kills_process_tree"]),
    ("M53", "M6 member env is an allow-list", "eq_harness.py",
     "else member_env(self.flags, self.stub))", "else None)",
     ["test_eqsec_proofs.py::test_m6_member_env_has_no_harness_secrets"]),
    ("M54", "M7 bounded digits in refs (no int() blow-up)", "eq_mediator.py",
     'm = re.fullmatch(r"(.+?):(\\d{1,9})(?:-\\d{1,9})?", ref.strip())',
     'm = re.fullmatch(r"(.+?):(\\d+)(?:-\\d+)?", ref.strip())',
     ["test_eqsec_proofs.py::test_m7_hostile_ref_is_a_status_not_a_crash"]),
    ("M55", "M8 special files skipped by copies", "eq_harness.py",
     "    shutil.copytree(src, dest, symlinks=True, ignore=ignore_specials)",
     "    shutil.copytree(src, dest, symlinks=True)",
     ["test_eqsec_proofs.py::test_m8_special_files_neither_crash_nor_hang"]),
    ("M56", "M9 R3 counts members, not padded fact keys", "eq_mediator.py",
     "            if ver[x.member]:\n                members.add(x.member)",
     "            members.update(ver[x.member])  # type: ignore[arg-type]",
     ["test_eqsec_proofs.py::test_m9_r3_not_won_by_padding"]),
    ("M57", "M10 no pristine re-run of command facts about a member's own copy (CP, PF)", "eq_harness.py",
     '    if item.cls in flags.get("workdir_answer_classes", []) or item.cls in flags.get("answer_file", {}):',
     "    if False:",
     ["test_eqsec_proofs.py::test_m10_true_claim_about_own_copy_not_refuted"]),
    # ---- verifier LOW observations (proofs: tests/test_verifier_lows.py) ----
    ("M58", "LOW1 scoring copy keeps the owned paths pristine", "eq_harness.py",
     "check_copy(it, Path(rec[\"answer_workdir\"]), wdc, overlay=True, owned=owned_paths(it, flags))",
     "check_copy(it, Path(rec[\"answer_workdir\"]), wdc, overlay=True)",
     ["test_verifier_lows.py::test_low1_score_copy_keeps_tests_pristine"]),
    ("M59", "LOW2 CR test dir owned", "eq_harness.py",
     '"check_owned_paths": {"CP": ["tests"], "CR": ["tests"]},', '"check_owned_paths": {"CP": ["tests"]},',
     ["test_verifier_lows.py::test_low2_every_checkable_test_dir_is_owned"]),
    ("M60", "LOW3 overlay keeps the pristine exec bit", "eq_harness.py",
     "                os.fchmod(f.fileno(), mode)", "                pass",
     ["test_verifier_lows.py::test_low3_overlay_keeps_pristine_exec_bit_but_no_special_bits"]),
    ("M61", "LOW3 overlay never copies setuid/setgid/sticky", "eq_harness.py",
     "    return (stat.S_IMODE(pristine_mode) & 0o755) | stat.S_IWUSR | stat.S_IRUSR",
     "    return (stat.S_IMODE(pristine_mode) & 0o7777) | stat.S_IWUSR | stat.S_IRUSR",
     ["test_verifier_lows.py::test_low3_overlay_mode_pure"]),
    ("M62", "PF review: public check runs with a private TMPDIR", "eq_harness.py",
     "cwd, minimal_env(**extra, TMPDIR=str(tmp)),", "cwd, minimal_env(**extra),",
     ["test_pf_tmp.py::test_killed_check_leaks_no_workdir_and_fails"]),
    # ---- isolation backend: Apple container (proofs: tests/test_isolation.py, fake container CLI) ----
    ("M66", "container: --network none", "eq_harness.py",
     'cmd += ["--network", "none", "--read-only",', 'cmd += ["--read-only",',
     ["test_isolation.py::test_container_argv_has_every_required_flag_and_only_two_mounts"]),
    ("M67", "container: never mount home", "eq_harness.py",
     '        cmd += ["-w", workdir]', '        cmd += ["-v", f"{self.home}:/home:ro", "-w", workdir]',
     ["test_isolation.py::test_container_argv_has_every_required_flag_and_only_two_mounts"]),
    ("M68", "container: never mount the docker socket", "eq_harness.py",
     '        cmd += ["-w", workdir]',
     '        cmd += ["-v", "/var/run/docker.sock:/var/run/docker.sock", "-w", workdir]',
     ["test_isolation.py::test_container_argv_has_every_required_flag_and_only_two_mounts"]),
    ("M69", "container: image pinned by digest (tags refused)", "eq_harness.py",
     "    if not isinstance(ref, str) or not IMAGE_REF_RE.fullmatch(ref):", "    if not isinstance(ref, str):",
     ["test_isolation.py::test_tag_or_malformed_image_refused", "test_isolation.py::test_flags_cli_refuses_a_tag"]),
    ("M70", "container: fail closed when the services are down", "eq_harness.py",
     "        if rc != 0:\n            raise IsolationError(f\"the container services are not reachable",
     "        if False:\n            raise IsolationError(f\"the container services are not reachable",
     ["test_isolation.py::test_preflight_fails_closed", "test_isolation.py::test_run_fails_closed_before_any_call"]),
    ("M71", "container: kill the container on timeout", "eq_harness.py",
     "                self.kill(call.name)", "                pass",
     ["test_isolation.py::test_timeout_kills_the_container_by_name"]),
    ("M72", "container: orphan sweep", "eq_harness.py",
     '        rc, out = self._cli("list", "--all", "--format", "json")', '        rc, out = 1, ""',
     ["test_isolation.py::test_sweep_removes_orphans_of_one_arm"]),
    ("M73", "container: never mount home or an ancestor", "eq_harness.py",
     "        if self.home.is_relative_to(h):", "        if False:",
     ["test_isolation.py::test_forbidden_mounts_refused"]),
    ("M74", "container: never mount secrets, socket, oracle data, runs/", "eq_harness.py",
     "            if h.is_relative_to(f) or f.is_relative_to(h):", "            if False:",
     ["test_isolation.py::test_forbidden_mounts_refused"]),
    ("M75", "ledger: check records carry backend + image", "eq_harness.py",
     "member=i + 1, round=0, passed=ok, output_tail=out[-500:], **self.iso.tag(item.cls))",
     "member=i + 1, round=0, passed=ok, output_tail=out[-500:])",
     ["test_isolation.py::test_run_records_backend_and_sweeps_every_item_arm",
      "test_launch.py::test_ledger_fields_are_documented"]),
    ("M76", "one backend per ledger", "eq_harness.py",
     'if prev.get("record") == "run_start" and prev.get("isolation", desc) != desc:', "if False:",
     ["test_isolation.py::test_one_backend_per_ledger"]),
    ("M77", "sandbox-exec stub fails closed", "eq_harness.py",
     "        if self.backend == \"sandbox-exec\":\n            raise IsolationError(",
     "        if self.backend == \"sandbox-exec\":\n            return None or IsolationError(",
     ["test_isolation.py::test_preflight_fails_closed"]),
    ("M78", "isolated oracle sees only the listed oracle files", "eq_harness.py",
     "    rels = ([fixture] if fixture else []) + list(extra_paths)",
     '    rels = ([fixture] if fixture else []) + list(extra_paths) + ["oracle"]',
     ["test_isolation.py::test_isolated_oracle_stages_only_allowed_inputs"]),
    ("M79", "EQ_LEAN_TOTAL below the group kill (container start included)", "eq_harness.py",
     '    return max(1, int(timeout_s) - int(flags.get("check_deadline_margin_s", 60)))', "    return int(timeout_s)",
     ["test_isolation.py::test_run_check_goes_through_the_container",
      "test_isolation.py::test_default_flags_isolate_with_container"]),
    ("M80", "the container mounts the FRESH check copy, never the member's copy", "eq_harness.py",
     'rw_dirs={"/work": cdir}', 'rw_dirs={"/work": workdir}',
     ["test_isolation.py::test_run_check_goes_through_the_container"]),
    ("M81", "PF/CP oracles run isolated", "eq_harness.py",
     "    if iso is not None and iso.backend != \"off\" and cls in iso.oracle_classes:", "    if False:",
     ["test_isolation.py::test_isolated_oracle_stages_only_allowed_inputs"]),
    ("M82", "live mediator re-runs use the run's backend", "eq_harness.py",
     "execute=self.iso.fact_executor(item.cls, arm_key(item.id, label)))", "execute=None)",
     ["test_isolation.py::test_live_mediator_uses_the_runs_backend"]),
    ("M83", "offline-facts: same M10 rule as live", "eq_mediator.py",
     "public_check=eh.fact_public_check(item, flags),", "public_check=item.public_check,",
     ["test_isolation.py::test_offline_facts_use_the_live_m10_rule_and_backend"]),
    ("M63", "PF review: private TMPDIR removed after the run", "eq_harness.py",
     "        shutil.rmtree(d, ignore_errors=True)", "        pass",
     ["test_pf_tmp.py"]),
    ("M64", "PF review: oracle runs with a private TMPDIR", "eq_harness.py",
     "rc, out = run_bounded(argv, pool, minimal_env(TMPDIR=str(tmp)), timeout, stdin_data=stdin)",
     "rc, out = run_bounded(argv, pool, minimal_env(), timeout, stdin_data=stdin)",
     ["test_pf_tmp.py::test_oracle_gets_private_tmpdir"]),
    # R1 (security review of isolate(), 2026-10-04): each fix reverted must fail its proof test
    ("M84", "R1 F1: only the EQV1 <nonce> line is the verdict", "eq_harness.py",
     "    if cls not in EQV1_CLASSES:\n        return rc, out", "    if True:\n        return rc, out",
     ["test_isolation.py::test_isolated_oracle_ignores_unauthenticated_verdict",
      "test_isolation.py::test_r1_f1_host_oracle_nonce_on_stdin_and_one_verdict_line"]),
    ("M85", "R1 F1: the isolated oracle gets the nonce on stdin (-i)", "eq_harness.py",
     "                                   stdin=stdin)", "                                   stdin=None)",
     ["test_isolation.py::test_isolated_oracle_stages_only_allowed_inputs"]),
    ("M86", "R1 F1: the host oracle gets the nonce on stdin", "eq_harness.py",
     "minimal_env(TMPDIR=str(tmp)), timeout, stdin_data=stdin)", "minimal_env(TMPDIR=str(tmp)), timeout)",
     ["test_isolation.py::test_r1_f1_host_oracle_nonce_on_stdin_and_one_verdict_line"]),
    ("M87", "R1 F2: sweeps filter on this invocation (eq-inv)", "eq_harness.py",
     'if lab.get("eq-harness") == "1" and lab.get("eq-inv") == self.inv\n',
     'if lab.get("eq-harness") == "1"\n',
     ["test_isolation.py::test_r1_f2_sweep_removes_only_this_invocations_containers"]),
    ("M88", "R1 F2: another invocation's containers are removed only once stale", "eq_harness.py",
     "and now - int(started) > self.stale_after_s()):", "):",
     ["test_isolation.py::test_r1_f2_sweep_removes_only_this_invocations_containers"]),
    ("M89", "R1 F3: a failed run with the services or image gone raises IsolationError", "eq_harness.py",
     "                self.require_services_and_image(call.image)\n", "                pass\n",
     ["test_isolation.py::test_r1_f3_services_or_image_lost_raises",
      "test_isolation.py::test_cli_or_code_failure_is_never_a_pass"]),
    ("M137", "container: the TAG's digest is checked right before every run", "eq_harness.py",
     '            self.require_image(call.image, " before the run")\n', "            pass\n",
     ["test_isolation.py::test_r1_f8_digest_checked_before_and_after_every_run"]),
    ("M138", "container: and again after a passing run (no PASS from a swapped image)", "eq_harness.py",
     '                self.require_image(call.image, " after the run")\n', "                pass\n",
     ["test_isolation.py::test_r1_f8_an_image_swapped_during_the_run_is_an_isolation_error",
      "test_isolation.py::test_r1_f8_digest_checked_before_and_after_every_run"]),
    ("M139", "container: the digest must be unambiguous (inspect paths agree)", "eq_harness.py",
     "    return found.pop() if len(found) == 1 else None", "    return found.pop() if found else None",
     ["test_isolation.py::test_inspect_digest_shapes", "test_isolation.py::test_preflight_fails_closed"]),
    ("M140", "container: limits validated before they reach the argv", "eq_harness.py",
     "        if (nproc < 1 or not all(SIZE_RE.fullmatch(s) for s in (mem, tmp, work))",
     "        if False and (nproc < 1 or not all(SIZE_RE.fullmatch(s) for s in (mem, tmp, work))",
     ["test_isolation.py::test_malformed_limits_never_reach_the_argv"]),
    ("M90", "R1 F3: cmd_run records run_abort", "eq_harness.py",
     'ledger.append("run_abort", ', '(lambda *a, **k: None)("run_abort", ',
     ["test_isolation.py::test_r1_f3_run_records_run_abort_and_exits_2"]),
    ("M91", "R1 F3: a fact re-run never turns lost services into a status", "eq_mediator.py",
     "                except eh.IsolationError:  # isolation lost (R1 F3): the run stops, never a fact status\n"
     "                    raise\n", "",
     ["test_isolation.py::test_r1_f3_services_or_image_lost_raises"]),
    ("M92", "R1 F4: /work is a capped tmpfs over a read-only bind", "eq_harness.py",
     '                    "--tmpfs", f"{ctr}:size={work_size},mode=1777"]\n'
     '            copy_in += [f"{CTR_SRC}{ctr}", ctr]',
     '                    "-v", f"{host.resolve()}:{ctr}:rw"]',
     ["test_isolation.py::test_r1_f4_work_is_a_capped_tmpfs_over_a_readonly_bind",
      "test_isolation.py::test_r1_f4_writes_to_work_never_reach_the_host_copy"]),
    ("M93", "container 1.5.0: only options `container run --help` lists (no pids limit)", "eq_harness.py",
     '"--ulimit", f"nproc={nproc}",', '"--ulimit", f"nproc={nproc}", "--pids-limit", str(nproc),',
     ["test_isolation.py::test_only_options_the_container_help_lists"]),
    ("M94", "R1 F6: the check script runs from the read-only fixture", "eq_harness.py",
     "                argv, more = pristine_check_inputs(item, self.flags, cdir)",
     "                more = pristine_check_inputs(item, self.flags, cdir)[1]",
     ["test_isolation.py::test_r1_f6_check_script_and_its_inputs_come_from_the_readonly_fixture",
      "test_isolation.py::test_run_check_goes_through_the_container"]),
    ("M95", "R1 F6: owned tests mounted read-only over /work", "eq_harness.py",
     '        ro[f"/work/{rel}"] = src', "        continue",
     ["test_isolation.py::test_r1_f6_owned_tests_are_mounted_readonly_over_work"]),
    ("M96", "R1 F7: the probe's main container is built by isolate()", "eq_harness.py",
     "            rows = harness_probe(iso, users[0], inner)", "            rows = []",
     ["test_isolation.py::test_r1_f7_isolation_probe_runs_isolate_argv"]),
    ("M97", "R1 F7: probe.sh gets the flags.json images", "eq_harness.py",
     '    env["EQ_PROBE_IMAGES"] = " ".join(iso.image_for(c) for c in ("PF", "CP") if c in classes)',
     '    env["EQ_PROBE_IMAGES"] = ""',
     ["test_isolation.py::test_r1_f7_isolation_probe_runs_isolate_argv"]),
    ("M98", "R1 F8: the run names the TAG (a local image is found by name only; digest checked)", "eq_harness.py",
     '        cmd.append(image.rpartition("@")[0])', "        cmd.append(image)",
     [T_ARGV, "test_isolation.py::test_r1_f8_digest_checked_before_and_after_every_run"]),
    ("M65", "PF review: fact runs get a private TMPDIR each", "eq_mediator.py",
     "eh.minimal_env(TMPDIR=str(tmp))", "eh.minimal_env()",
     ["test_pf_tmp.py::test_fact_runs_get_private_tmpdir"]),
    ("M39", "A1.2 chaining: latest dependency in topological order", "eq_harness.py",
     "key=lambda d: (lv.get(d, 0), d))", "key=lambda d: d)",
     ["test_review_fixes.py::test_chain_source_only_for_workdir_classes"]),
    # ---- the WALL and its ONE tunnel (../wall/WALL_DESIGN.md §8) --------------------------------------------------
    ("M99", "WALL: /eq is reserved for the tunnel", "eq_harness.py",
     " or ctr == CTR_EQ\n                or ctr.startswith(CTR_EQ + \"/\")):", "):",
     ["test_wall_integration.py::test_tunnel_mount_refusals"]),
    ("M100", "WALL: the tunnel is a real 0700 dir owned by the user", "eq_harness.py",
     "        if not stat.S_ISDIR(st.st_mode) or st.st_uid != os.getuid() or st.st_mode & 0o077:\n"
     "            raise IsolationError(f\"tunnel", "        if False:\n            raise IsolationError(f\"tunnel",
     ["test_wall_integration.py::test_tunnel_mount_refusals"]),
    ("M101", "WALL: the tunnel exists only under the container backend", "eq_harness.py",
     "        if tunnel is not None and self.backend != \"container\":\n            raise",
     "        if False:\n            raise",
     ["test_wall_integration.py::test_tunnel_mount_refusals"]),
    ("M102", "WALL: broker bytes hash to the frozen value before they run", "eq_harness.py",
     "    if hashlib.sha256(data).hexdigest() != want_sha256:", "    if False:",
     ["test_wall_integration.py::test_wall_refuses_any_change_to_the_frozen_configuration"]),
    ("M103", "WALL: policy frozen", "eq_harness.py",
     'if not self.policy.is_file() or sha256_file(self.policy) != cfg["policy_sha256"]:',
     "if not self.policy.is_file():",
     ["test_wall_integration.py::test_wall_refuses_any_change_to_the_frozen_configuration"]),
    ("M104", "WALL: tunnel/broker config frozen", "eq_harness.py",
     '        if (cfg.get("mechanism") != self.ew.MECHANISM', '        if False and (cfg.get("mechanism") != '
     'self.ew.MECHANISM',
     ["test_wall_integration.py::test_wall_refuses_any_change_to_the_frozen_configuration"]),
    ("M105", "WALL: the probe receipt must say PASS", "eq_harness.py",
     'if not isinstance(rec, dict) or rec.get("result") != "PASS":', "if not isinstance(rec, dict):",
     ["test_wall_integration.py::test_probe_receipt_gate"]),
    ("M106", "WALL: the receipt is bound to the config hash", "eq_harness.py",
     '        if rec.get("config_sha256") != self.cfg["config_sha256"]:', "        if False:",
     ["test_wall_integration.py::test_probe_receipt_gate"]),
    ("M107", "WALL: run refuses without a PASSing probe", "eq_harness.py",
     "            wall.check_probe(sorted(", "            (lambda *_: None)(sorted(",
     ["test_wall_integration.py::test_run_refuses_without_a_passing_tunnel_probe"]),
    ("M108", "WALL: one WALL/member_exec configuration per ledger", "eq_harness.py",
     '        if prev.get("record") == "run_start" and (\n', '        if False and (\n',
     ["test_wall_integration.py::test_run_with_the_wall_records_nonce_channels_and_audit"]),
    ("M109", "member exec: Bash replaced by the sandbox tool", "eq_harness.py",
     '        return [MEMBER_EXEC_TOOL if t == "Bash" else t for t in tools], True', "        return tools, True",
     ["test_wall_integration.py::test_member_tools_replace_bash_only_in_sandbox_mode"]),
    ("M110", "member exec: tool input validated", "eq_harness.py",
     '\n            or any(not isinstance(a, str) or "\\0" in a or len(a) > 8192 for a in argv)', "",
     ["test_wall_integration.py::test_member_exec_server_runs_argv_in_the_sandbox"]),
    ("M111", "WALL: audit chain verified before import", "eq_harness.py",
     "            recs: list[dict[str, Any]] = self.ew.verify_audit(self.audit_path)",
     "            recs = [json.loads(x) for x in self.audit_path.read_text().splitlines()]",
     ["test_wall_integration.py::test_broken_audit_chain_is_an_isolation_error"]),
    ("M112", "WALL: only the nonce's sha256 reaches the ledger", "eq_harness.py",
     '"nonce_sha256": None if self.nonce is None else sha256_text(self.nonce),', '"nonce_sha256": self.nonce,',
     ["test_wall_integration.py::test_run_with_the_wall_records_nonce_channels_and_audit"]),
    ("M113", "WALL: nonce revealed beside the audit log at run end (replay)", "eq_harness.py",
     "                self.ew.reveal_nonce(self.state, self.run_id, self.nonce)", "                pass",
     ["test_wall_integration.py::test_run_with_the_wall_records_nonce_channels_and_audit"]),
    ("M114", "isolation-probe runs the tunnel case", "eq_harness.py",
     "                trows = tunnel_probe(iso, users[0], wall, tscript)", "                trows = []",
     ["test_wall_integration.py::test_isolation_probe_runs_the_tunnel_case_and_writes_the_receipt"]),
    ("M115", "50-tunnel.sh hook mode prints T| rows (probe.sh section G contract)", TUNNEL_SH,
     '  for r in "${trows[@]}"; do echo "$r"; done', "  :",
     ["test_wall_integration.py::test_tunnel_hook_meets_the_probe_d_contract"]),
    ("M116", "50-tunnel.sh hook mode probes the image probe.sh names", TUNNEL_SH,
     '[ -z "$hook" ] || img=${EQ_PROBE_IMAGE:?', '[ -n "$hook" ] || img=${EQ_PROBE_IMAGE:?',
     ["test_wall_integration.py::test_tunnel_hook_meets_the_probe_d_contract",
      "test_wall_integration.py::test_tunnel_hook_without_the_probe_image_stops_before_any_container_call"]),
    ("M117", "50-tunnel.sh: a failed precondition is a FAIL row, never a silent exit",
     TUNNEL_SH,
     '  if [ -n "$hook" ]; then echo "T|$1|FAIL|$2"; else', '  if false; then echo "T|$1|FAIL|$2"; else',
     ["test_wall_integration.py::test_tunnel_hook_reports_a_fail_row_when_the_services_are_down"]),
    ("M118", "isolation-probe: every in-container tunnel row is required", "eq_harness.py",
     "                 for n in TUNNEL_PROBE_REQUIRED if n not in seen]", "                 for n in ()]",
     ["test_wall_integration.py::test_isolation_probe_requires_every_tunnel_row"]),
    ("M119", "isolation-probe: a tunnel row result other than PASS/FAIL/INFO is a FAIL", "eq_harness.py",
     'g[1] if g[1] in ("PASS", "FAIL", "INFO") else "FAIL"', "g[1]",
     ["test_wall_integration.py::test_isolation_probe_requires_every_tunnel_row"]),
    ("M120", "WALL: every channel carries the hash-checked client", "eq_harness.py",
     "                f.write(self.client_bytes)", "                pass",
     ["test_wall_integration.py::test_each_channel_carries_the_frozen_client"]),
    ("M121", "WALL: the receipt's required rows are re-checked at run", "eq_harness.py",
     "        missing = [n for n in (*TUNNEL_PROBE_REQUIRED, *TUNNEL_PROBE_HOST_ROWS) "
     "if n not in {r[0] for r in rows}]",
     "        missing = []",
     ["test_wall_integration.py::test_probe_receipt_rows_are_revalidated"]),
    ("M122", "WALL: a FAIL row in a PASS receipt is refused", "eq_harness.py",
     '        bad = [f"{r[0]} {r[1]}" for r in rows if r[1] not in ("PASS", "INFO")]', "        bad = []",
     ["test_wall_integration.py::test_probe_receipt_rows_are_revalidated"]),
    ("M123", "WALL: the broker that started reports the frozen hashes (W5)", "eq_harness.py",
     '        if start is None or (start.get("broker_sha256"), start.get("policy_sha256")) != (',
     '        if start is not None and (start.get("broker_sha256"), start.get("policy_sha256")) == (',
     ["test_wall_integration.py::test_the_broker_that_starts_must_be_the_frozen_one"]),
    ("M124", "WALL: close_channel waits out a busy serial broker (N24#3)", "eq_harness.py",
     '        stall = max(timeout_s, float(self.limits["exec_timeout_s"]) + 60.0)', "        stall = timeout_s",
     ["test_wall_integration.py::test_close_channel_waits_for_a_busy_broker"]),
    ("M125", "WALL: broker.stderr is 0600 (N24#6)", "eq_harness.py",
     "os.O_CLOEXEC, 0o600)\n        err = os.fdopen(efd", "os.O_CLOEXEC, 0o644)\n        err = os.fdopen(efd",
     ["test_wall_integration.py::test_broker_stderr_is_private"]),
    ("M126", "member exec: the eqbox server reads no uv config, fixed cwd", "eq_harness.py",
     '"args": ["run", "--no-config", "--directory", "/", "--script", "--quiet",',
     '"args": ["run", "--script", "--quiet",',
     ["test_wall_integration.py::test_eqbox_server_reads_no_uv_config_and_runs_from_a_fixed_cwd"]),
    ("M127", "score no_verdict_policy 'zero' scores a verdict-less re-run 0", "eq_harness.py",
     "                    scored_zero = no_score(out)", "                    scored_zero = False",
     ["test_no_verdict_policy.py::test_zero_policy_reruns_once_then_scores_zero"]),
    ("M128", "score no_verdict_policy 'zero' re-checks isolation first", "eq_harness.py",
     "                        iso.preflight([a.cls])\n", "                        pass\n",
     ["test_no_verdict_policy.py::test_zero_policy_never_scores_when_isolation_is_unhealthy"]),
    ("M129", "eq_check E12 torn/truncated last line", "eq_check.sh",
     """[ "$(tail -c 1 "$LEDGER" | od -An -tx1 | tr -d ' \\n')" = 0a ] || lerr=""", "true || lerr=",
     ["test_shell.py::test_check_fault_torn_or_truncated_ledger"]),
    ("M130", "eq_check E12 seq = line number", "eq_check.sh",
     '($o | type) != "object" or $o.seq != $e.key + 1', '($o | type) != "object"',
     ["test_shell.py::test_check_fault_torn_or_truncated_ledger"]),
    ("M131", "WALL: the receipt's host-side rows are required at run (R2b a)", "eq_harness.py",
     "for n in (*TUNNEL_PROBE_REQUIRED, *TUNNEL_PROBE_HOST_ROWS) if n not in",
     "for n in TUNNEL_PROBE_REQUIRED if n not in",
     ["test_wall_integration.py::test_probe_receipt_requires_the_host_side_rows"]),
    ("M132", "score 'zero': an authenticated null verdict triggers the re-run (R2c F1)", "eq_harness.py",
     'if no_verdict == "zero" and a.cls in EQV1_CLASSES and no_score(out):',
     'if no_verdict == "zero" and a.cls in EQV1_CLASSES and NO_VERDICT_RE.match(out):',
     ["test_no_verdict_policy.py::test_zero_policy_scores_an_authenticated_null_verdict_zero"]),
    ("M133", "score 'zero': a null verdict after the re-run scores 0 (R2c F1)", "eq_harness.py",
     "                    scored_zero = no_score(out)",
     "                    scored_zero = bool(NO_VERDICT_RE.match(out))",
     ["test_no_verdict_policy.py::test_zero_policy_scores_an_authenticated_null_verdict_zero"]),
    ("M134", "no_score: a JSON verdict is needed (a host oracle error is never zeroed)", "eq_harness.py",
     '    return bool(res) and parse_score(res.get("score")) is None',
     '    return parse_score(res.get("score")) is None',
     ["test_no_verdict_policy.py::test_zero_policy_never_zeroes_a_host_side_oracle_error"]),
    ("M135", "score 'zero': a null verdict's detail names it", "eq_harness.py",
     '"detail": NO_VERDICT_DETAIL if NO_VERDICT_RE.match(out) else NULL_VERDICT_DETAIL,',
     '"detail": NO_VERDICT_DETAIL,',
     ["test_no_verdict_policy.py::test_zero_policy_scores_an_authenticated_null_verdict_zero"]),
    ("M136", "no_verdict_policy default 'zero' (USER 2026-10-05, COMPARE_eq A3)", "eq_harness.py",
     '    "no_verdict_policy": "zero",', '    "no_verdict_policy": "unscored",',
     ["test_no_verdict_policy.py::test_default_policy_is_zero"]),
    # COMPARE_eq §12 A6 (2026-10-07): member grade files, E_rt bundle_mismatch, underflow, cells, LOO wiring
    ("M141", "member grades: EG E-node members are never member units", "eq_harness.py",
     'if r.get("record") != "call" or r.get("cls") != cls or r.get("node") is not None:',
     'if r.get("record") != "call" or r.get("cls") != cls:',
     ["test_member_grades.py::test_member_units_selects_member_calls_latest_wins"]),
    ("M142", "member grades: a forked round is graded on its branch_workdir", "eq_harness.py",
     '"workdir": r.get("branch_workdir") or r.get("cwd")}', '"workdir": r.get("cwd")}',
     ["test_member_grades.py::test_score_members_cp_grades_a_check_copy_of_the_member_dir"]),
    ("M143", "score: CP grades a check copy, never the member's own dir", "eq_harness.py",
     '                extra = ["--workdir", str(wdc)]\n',
     '                extra = ["--workdir", rec["answer_workdir"]]\n',
     ["test_member_grades.py::test_score_members_cp_grades_a_check_copy_of_the_member_dir"]),
    ("M144", "CR_findings: a duplicate takes its kept index's grade", "eq_harness.py",
     "p = per.get(i) or per.get(k)", "p = per.get(i)",
     ["test_member_grades.py::test_cr_finding_rows_take_the_kept_index_grade"]),
    ("M145", "CR_findings: member findings outside EG nodes only", "eq_harness.py",
     "if member is not None and node is None and rc == 0:", "if member is not None and rc == 0:",
     ["test_member_grades.py::test_cr_grade_writes_member_findings"]),
    ("M146", "rs-grader-input: mechanically settled answers leave the batch", "eq_harness.py",
     '"needs_grade": det.get("mechanical") is True,', '"needs_grade": True,',
     ["test_member_grades.py::test_rs_members_end_to_end_with_the_real_oracle"]),
    ("M147", "rs member units: each p7 branch result as member 0", "eq_harness.py",
     'if r.get("record") == "item_arm" and r.get("cls") == "RS" and r.get("cell") == "p7" \\',
     'if r.get("record") == "item_arm" and r.get("cls") == "RS" and r.get("cell") == "p6" \\',
     ["test_member_grades.py::test_rs_member_units_add_each_p7_branch_as_member_0"]),
    ("M148", "rs-grade: a missing verdict is refused", "eq_harness.py",
     '    problems += [f"missing verdict for {r}" for r in sorted(want - set(out))]\n', "",
     ["test_member_grades.py::test_rs_split_verdicts_validates"]),
    ("M149", "E_rt: a plan bundle other than --params' is bundle_mismatch", "eq_harness.py",
     "            if got != exp:  # the runtime resolved another bundle", "            if False:  # the runtime "
     "resolved another bundle", ["test_e_rt.py::test_bundle_mismatch_stops_before_start"]),
    ("M150", "E_rt: every bundle key non-null in --params (member_model_id too)", "eq_harness.py",
     "BUNDLE_REQUIRED = BUNDLE_KEYS  #", "BUNDLE_REQUIRED = BUNDLE_KEYS[2:]  #",
     ["test_e_rt.py::test_eq_store_dir_and_bundle_helpers"]),
    ("M151", "E_rt: stage q needs --params", "eq_harness.py",
     '    elif a.e_arm == "runtime" and a.stage == "q":\n', "    elif False:\n",
     ["test_e_rt.py::test_run_refuses_bad_params"]),
    ("M152", "analysis: a bundle_mismatch item-arm leaves route 1", "eq_analyse.py",
     'if pick.get("bundle_mismatch") is not None:', "if False:",
     ["test_eq_analyse.py::test_bundle_mismatch_e_rt_arm_leaves_route_1"]),
    ("M153", "underflow: abs_ln_ratio of an underflowing ratio", "eq_harness.py",
     "return abs(math.log(r)) if r > 0 else abs(math.log(a) - math.log(b))", "return abs(math.log(r))",
     ["test_underflow.py::test_harness_numeric_helpers_survive_underflow"]),
    ("M154", "underflow: mediator numeric clusters", "eq_mediator.py",
     '"near" if eh.abs_ln_ratio(v, med) <= math.log(2) + 1e-12 else "far")',
     '"near" if abs(math.log(v / med)) <= math.log(2) + 1e-12 else "far")',
     ["test_underflow.py::test_mediator_numeric_clusters_survive_underflow"]),
    ("M155", "cells: cell rows continue the arm rows' seq", "eq_harness.py",
     "seq = max((r.seq for r in rows), default=0)", "seq = 0",
     ["test_cells.py::test_cell_rows_are_appended_after_an_unchanged_prefix"]),
    ("M156", "cells: run without --cells skips the cell rows", "eq_harness.py",
     "rows = [r for r in all_rows if (r.arm in a.cells if a.cells else r.arm not in CELLS)]",
     "rows = [r for r in all_rows if (r.arm in a.cells if a.cells else True)]",
     ["test_cells.py::test_run_without_cells_skips_the_cell_rows"]),
    ("M157", "p6: 9 members at the N = 5 per-member cap", "eq_harness.py",
     'c5 = caps_enode(self.b_micro(item), family, int(self.flags["N"]), r_max, self.flags,',
     "c5 = caps_enode(self.b_micro(item), family, n, r_max, self.flags,",
     ["test_cells.py::test_p6_nine_members_at_the_n5_cap_tagged"]),
    ("M158", "forks: round k forks the member's latest session (r2 <- r1)", "eq_harness.py",
     "                if rr.session_id is not None:\n                    chain[i] = rr.session_id\n",
     "                if rr.session_id is not None:\n                    pass\n",
     ["test_cells.py::test_p7_four_branches_two_forced_rounds_forked_from_p3"]),
    ("M159", "blinding: cell labels p6/p7 are role tokens", "eq_harness.py",
     'ROLE_TOKEN_RE = re.compile(r"\\b(?:[pq][1-9]|m\\d+/\\d+)\\b")',
     'ROLE_TOKEN_RE = re.compile(r"\\b(?:[pq][1-5]|m\\d+/\\d+)\\b")',
     ["test_cells.py::test_role_token_re_redacts_cell_labels"]),
    ("M160", "LOO views: the shown view leaves the excluded member out", "eq_harness.py",
     "        return render(e), e\n", "        return render(None), e\n",
     ["test_wiring.py::test_views_shown_match_the_exclusion"]),
    ("M161", "LOO views: rotation e_r(i) = (i - 1 + r) mod N + 1", "eq_mediator.py",
     "        e = (p + r) % n\n", "        e = (p + r + 1) % n\n",
     ["test_wiring.py::test_reconcile_calls_record_the_variant_and_its_exclusion"]),
    ("M162", "per-round attribution after every reconcile round", "eq_harness.py",
     "            self.loo_round(med, rnd, seed_key)\n            if not changed_any and not forced:",
     "            if not changed_any and not forced:",
     ["test_wiring.py::test_per_round_attribution_lambda_by_hand"]),
    # COMPARE_eq §12 A8: E7 for a cell pass (eq_check.sh <ITEM> <stage> <cells>)
    ("M163", "eq_check E7: a cell pass has its own rule, not the arm pass's", "eq_check.sh",
     'elif [ -n "$CELLS" ]; then', "elif false; then",
     ["test_shell.py::test_check_cell_pass_follows_the_arm_rule_order"]),
    ("M164", "eq_check E7 cell pass: every item has an arm-check PASS line first", "eq_check.sh",
     "elif ($unchecked | length) > 0 then", "elif false then",
     ["test_shell.py::test_check_cell_pass_waits_for_every_arm_check"]),
    ("M165", "eq_check E7 cell pass: the next item in schedule order, or a re-check of the last cell PASS",
     "eq_check.sh", "elif $i == $next or ($i == $lastcell and", "elif true or ($i == $lastcell and",
     ["test_shell.py::test_check_cell_pass_follows_the_arm_rule_order"]),
    ("M166", "eq_check E7 cell pass: a started cell row is not run again", "eq_check.sh",
     'elif $held[$i] then "started"', 'elif false then "started"',
     ["test_shell.py::test_check_cell_pass_follows_the_arm_rule_order"]),
    ("M167", "eq_check E7 cell pass: done cell rows are not to do", "eq_check.sh",
     'select(mine($C)) | select($done[.[2] + "\\t" + .[5]] | not)] as $todo', "select(mine($C))] as $todo",
     ["test_shell.py::test_check_cell_pass_follows_the_arm_rule_order"]),
    ("M168", "eq_check: <cells> is refused at stage q", "eq_check.sh",
     'if [ -n "$CELLS" ] && [ "$STAGE" = q ]; then', "if false; then",
     ["test_shell.py::test_check_refuses_a_bad_cells_argument"]),
    ("M171", "eq_check E7 cell pass: the last arm-checked item has no arm row left to run", "eq_check.sh",
     'elif ($armcall[$lastarm // ""] | not) and', "elif false and",
     ["test_shell.py::test_check_cell_pass_waits_for_the_last_arm_item"]),
    ("M172", "eq_check E7 cell pass: a held item (started cell row) does not stop the pass", "eq_check.sh",
     "select(($held[$x] | not) and", "select(true and",
     ["test_shell.py::test_check_cell_pass_moves_past_a_held_item"]),
    ("M173", "eq_check E7 cell pass: an item's cell checks cover its rows (no second check)", "eq_check.sh",
     '($checked[$x + "\\t" + .[4]] | not)', "true",
     ["test_shell.py::test_check_cell_pass_follows_the_arm_rule_order"]),
    ("M174", "eq_check: a cell check's log line carries <cells>", "eq_check.sh",
     '"${fails# }" \\\n  "$CELLS" >> "$LOG"', '"${fails# }" \\\n  "" >> "$LOG"',
     ["test_shell.py::test_check_cell_pass_follows_the_arm_rule_order"]),
    ("M175", "eq_check E7 arm rule: a cell check's PASS line is not its last PASS", "eq_check.sh",
     '$3=="PASS" && $7==""{p=$2}', '$3=="PASS"{p=$2}',
     ["test_shell.py::test_check_arm_rule_reads_only_arm_check_lines"]),
    ("M176", "eq_check E7 cell re-check: the last cell line named each of the item's not-done cells", "eq_check.sh",
     '.[4] as $a | (($lastline[6] // "") | split(",") | any(.[]; . == $a))', "true",
     ["test_shell.py::test_check_cell_recheck_covers_only_the_cells_its_line_named"]),
    ("M177", "eq_check E7 cell pass: next only if no not-done row of the item is covered", "eq_check.sh",
     "and all($todo[] | select(.[2] == $x);", "and any($todo[] | select(.[2] == $x);",
     ["test_shell.py::test_check_cell_pass_never_reruns_a_covered_row"]),
    ("M169", "run --cells passes its cells to eq_check.sh", "eq_harness.py",
     'item_id, a.stage, *([",".join(a.cells)] if a.cells else [])]', "item_id, a.stage]",
     ["test_shell.py::test_cell_pass_runs_through_eq_check_after_the_arm_pass"]),
    ("M170", "run --cells takes distinct cells", "eq_harness.py",
     "or len(set(cells)) != len(cells) or (cells and", "or (cells and",
     ["test_cells.py::test_run_cells_refusals"]),
    # COMPARE_eq §12 A4 (ids A4m*: kept apart from the numbered series)
    ("A4m1", "A4: the tool list goes on --tools", "eq_harness.py",
     '    argv += ["--tools", tools_value(allowed_tools)]\n', "",
     ["test_skill_tools_argv.py::test_exact_argv_per_class"]),
    ("A4m2", "A4: Skill appended for every class", "eq_harness.py",
     "    tools += [t for t in common if t not in tools]\n", "",
     ["test_skill_tools_argv.py::test_exact_argv_per_class", "test_launch.py::test_launched_argv_and_heads"]),
    ("A4m3", "A4: one tool list for every arm and role of a class", "eq_harness.py",
     "        tools, boxed = member_tools(self.flags, item.cls)\n",
     "        tools, boxed = member_tools(self.flags, item.cls)\n"
     '        tools = tools if role == "s" else tools[:-1]\n',
     ["test_skill_tools_argv.py::test_same_tool_list_in_every_arm_and_role"]),
    ("A4m4", "A4: StructuredOutput named in --tools (--json-schema)", "eq_harness.py",
     'return ",".join(dict.fromkeys([*names, SCHEMA_TOOL]))', 'return ",".join(dict.fromkeys(names))',
     ["test_skill_tools_argv.py::test_exact_argv_per_class"]),
    ("A4m5", "A4: MCP tools stay off --tools", "eq_harness.py",
     'names = [str(t) for t in tools if not str(t).startswith("mcp__")]', "names = [str(t) for t in tools]",
     ["test_skill_tools_argv.py::test_boxed_member_keeps_mcp_out_of_tools"]),
    ("A4m6", "A4: flags.json carries common_tools Skill", "flags.json",
     ' "common_tools": [\n  "Skill"\n ],', ' "common_tools": [],',
     ["test_skill_tools_argv.py::test_disk_flags_match_default_on_common_tools"]),
]


def make_copy(root: Path) -> Path:
    st = root / "STAGE"
    st.mkdir(parents=True)
    for f in ("COMPARE_eq.md", "PROPOSAL.md", "MEDIATOR.md", "seeds.out"):
        shutil.copy(STAGE / f, st / f)
    shutil.copytree(HARNESS, st / "harness", symlinks=True,
                    ignore=shutil.ignore_patterns("__pycache__", ".pytest_cache", "*.pyc"))
    if (STAGE / "wall").is_dir():  # the WALL broker/client/policy and the tunnel probe (test_wall_integration.py)
        shutil.copytree(STAGE / "wall", st / "wall", ignore=shutil.ignore_patterns("__pycache__", "tests", ".*"))
    if (STAGE / "isolation" / "probe.d").is_dir():
        shutil.copytree(STAGE / "isolation" / "probe.d", st / "isolation" / "probe.d")
    cdir = container_dir()  # lib/eq-container: the tunnel probe's host mode (lib.sh, eqc_json.py) and its mutants
    if cdir is not None:
        shutil.copytree(cdir, st / "lib" / "eq-container", symlinks=True,
                        ignore=shutil.ignore_patterns("__pycache__", ".state"))
    if (STAGE / "items").is_dir():  # the real pools, read only (the RS oracle, stage q draws): linked, never mutated
        (st / "items").symlink_to(STAGE / "items")
    return st / "harness"


def pytest(h: Path, sel: list[str]) -> int:
    args = [sys.executable, "-m", "pytest", "-q", "-x", "-p", "no:cacheprovider", *[str(h / "tests" / s) for s in sel]]
    env = {k: v for k, v in os.environ.items() if k != "EQ_CONTAINER_DIR"}  # the copy's lib/eq-container, mutated
    return subprocess.run(args, cwd=h.parent, capture_output=True, text=True, check=False, env=env).returncode


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    muts = MUTATIONS
    if argv[:1] == ["--only"] and len(argv) == 2:
        want = argv[1].split(",")
        muts = [m for m in MUTATIONS if m[0] in want]
        if len(muts) != len(set(want)):
            print(f"--only: unknown ids {sorted(set(want) - {m[0] for m in muts})}", file=sys.stderr)
            return 2
    elif argv:
        print("usage: mutations.py [--only ID,ID,...]", file=sys.stderr)
        return 2
    bad = 0
    with tempfile.TemporaryDirectory(prefix="eqmut") as td:
        base = make_copy(Path(td) / "base")
        sels = sorted({s for m in muts for s in m[5]})
        rc = pytest(base, sels)
        print(f"BASE  unmutated copy, {len(sels)} selections: {'PASS' if rc == 0 else f'FAIL (exit {rc})'}")
        bad += rc != 0
        for mid, what, fname, old, new, sel in muts:
            if fname == TUNNEL_SH and container_dir() is None:
                print(f"{mid}  SKIPPED  {what}: lib/eq-container not found (set EQ_CONTAINER_DIR)")
                continue
            h = make_copy(Path(td) / mid)
            src = (h / fname).read_text()
            pairs = old if isinstance(old, list) else [(old, new)]
            counts = [src.count(o) for o, _ in pairs]
            if counts != [1] * len(pairs):
                print(f"{mid}  {what}: mutation anchor counts {counts} (ERROR)")
                bad += 1
                continue
            for o, nw in pairs:
                src = src.replace(o, nw)
            (h / fname).write_text(src)
            old = pairs[0][0]
            new = pairs[0][1]
            rc = pytest(h, sel)
            verdict = "KILLED" if rc != 0 else "SURVIVED"
            bad += rc == 0
            print(f"{mid}  {verdict:8s} (pytest exit {rc})  {what}  [{fname}: {old.strip()[:50]!r} -> "
                  f"{new.strip()[:50]!r}]")
    print(f"mutations: {len(muts)}, problems: {bad}")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
